Q1: Is there any difference in the data type of variables list_ and array_list? If there is, write a code to print the data types of both the variables.
Yes, there is a difference in the data type of the variables. list_ is a Python list, which can hold elements of different data types, while array_list is a NumPy array. NumPy arrays typically have a single data type (specified by the dtype argument), and all elements in the array are of the same type. In the given code, array_list will have the data type numpy.ndarray, and its elements will be strings (because list_ contains strings).

In [1]:
import numpy as np

# List and NumPy array
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data types
print("Data type of list_: ", type(list_))
print("Data type of array_list: ", type(array_list))

Data type of list_:  <class 'list'>
Data type of array_list:  <class 'numpy.ndarray'>


Q2: Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [2]:
import numpy as np

# List and NumPy array
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))

Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


Q3: Considering the following changes in the variable array_list:

In [3]:
import numpy as np

# List and NumPy array (with dtype=int)
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element in list_
print("Data type of each element in list_:")
for element in list_:
    print(type(element))

# Print data type of each element in array_list
print("\nData type of each element in array_list:")
for element in array_list:
    print(type(element))


Data type of each element in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Data type of each element in array_list:
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


Q4: Write a code to find the following characteristics of the variable num_array:
(i) Shape
(ii) Size

The shape attribute gives the dimensions of the array, and the size attribute gives the total number of elements in the array.

In [4]:
import numpy as np

# List and NumPy array
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

# Find shape and size
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5: Write a code to create a NumPy array of a 3x3 matrix containing zeros only, using a NumPy array creation function.

In [5]:
import numpy as np

# Create a 3x3 matrix with zeros
zeros_array = np.zeros((3, 3))

# Print the array
print("3x3 matrix of zeros:")
print(zeros_array)


3x3 matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6: Create an identity matrix of shape (5,5) using NumPy functions.

In [8]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Print the identity matrix
print("5x5 Identity Matrix:")
print(identity_matrix)

5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
